=== AcevedoR/outplant/event_chains/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Json schema for an event chain",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "cooldown": {
      "type": "integer",
      "minimum": 1
    },
    "trigger": {
      "type": "object",
      "properties": {
        "comparator": {
          "type": "string",
          "enum": [
            "lt",
            "lte",
            "eq",
            "gte",
            "gt"
          ]
        },
        "target": {
          "type": "string",
          "enum": [
            "population",
            "ecology",
            "money"
          ]
        },
        "value": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "required": [
        "comparator",
        "target",
        "value"
      ]
    },
    "events": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "text": {
            "type": "string"
          },
          "effects": {
            "type": "object",
            "additionalProperties": {
              "type": "boolean"
            }
          },
          "choices": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "text": {
                  "type": "string"
                },
                "next": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "event": {
                        "type": "string"
                      },
                      "in": {
                        "type": "integer",
                        "minimum": 0
                      },
                      "weight": {
                        "type": "number",
                        "exclusiveMinimum": 0
                      }
                    },
                    "required": [
                      "event"
                    ]
                  }
                }
              },
              "required": [
                "text",
                "next"
              ]
            }
          },
          "next": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "event": {
                  "type": "string"
                },
                "in": {
                  "type": "integer",
                  "minimum": 0
                },
                "weight": {
                  "type": "number",
                  "exclusiveMinimum": 0
                }
              },
              "required": [
                "event"
              ]
            }
          }
        },
        "additionalProperties": false,
        "required": [
          "text"
        ]
      },
      "required": [
        "start"
      ]
    },
    "effects": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "operation": {
            "type": "string",
            "enum": [
              "add",
              "subtract"
            ]
          },
          "target": {
            "type": "string",
            "enum": [
              "population",
              "ecology",
              "money"
            ]
          },
          "value": {
            "type": "number"
          },
          "type": {
            "type": "string",
            "enum": [
              "instant",
              "permanent"
            ]
          }
        },
        "additionalProperties": false,
        "required": [
          "operation",
          "target",
          "value",
          "type"
        ]
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "title",
    "trigger",
    "events"
  ]
}

=== AcevedoR/outplant/event_chains/rich_hunters.json
{
  "$schema": "./schema.json",
  "title": "rich hunters",
  "cooldown": 5,
  "trigger": {
    "comparator": "gt",
    "target": "population",
    "value": 8
  },
  "events": {
    "start": {
      "text": "You're contacted by some employees of very, very wealthy people. Their bosses are avid hunters and would be willing to pay loads of cash to be the first hunters of the species you're taking care of.",
      "choices": [
        {
          "text": "I guess just a fewer specimens won't hurt in the long run.",
          "next": [
            {
              "event": "base_payment_received"
            }
          ]
        },
        {
          "text": "What? Who do they think they are? I won't let them undo all my hard work!",
          "next": [
            {
              "event": "no_news_from_hunters",
              "weight": 3
            },
            {
              "event": "counter_offer_after_refusal"
            }
          ]
        }
      ]
    },
    "base_payment_received":{
      "text": "You receive 100 credits.",
      "effects": {
        "base_payment_received": true
      },
      "next": [
        {
          "event": "successful_hunt"
        },
        {
          "event": "unsuccessful_hunt"
        }
      ]
    },
    "double_payment_received": {
      "text": "You receive 200 credits.",
      "effects": {
        "double_payment_received": true
      },
      "next": [
        {
          "event": "successful_hunt"
        },
        {
          "event": "unsuccessful_hunt"
        }
      ]
    },
    "successful_hunt": {
      "text": "A few days pass before the hunters get on the planet and successfully hunt down 10 specimens of your species.",
      "effects": {
        "hunted_species": true
      },
      "next": [
        {
          "event": "no_news_from_hunters"
        },
        {
          "event": "hunters_want_to_hunt_again"
        }
      ]
    },
    "unsuccessful_hunt": {
      "text": "You receive 100 credits. A few days pass before the hunters get on the planet. It turns out they aren’t as good hunters as they think they are - they couldn’t capture even juvenile specimens and some of them are actually wounded.",
      "effects": {
        "base_payment_received": true
      },
      "choices": [
        {
          "text": "Pretend nothing has happened while they shamefully enter the medical bay",
          "next": [
            {
              "event": "no_news_from_hunters"
            }
          ]
        },
        {
          "text": "Praise them for being so skilled at “tactical retreat”",
          "next": [
            {
              "event": "no_news_from_hunters"
            }
          ]
        },
        {
          "text": "Try to blackmail them - either they become “generous donators” or everybody will know about just how poor hunters they are",
          "next": [
            {
              "event": "blackmail_success",
              "weight": 4
            },
            {
              "event": "blackmail_failure"
            }
          ]
        }
      ]
    },
    "no_news_from_hunters": {
      "text": "You never hear of the hunters again."
    },
    "hunters_want_to_hunt_again": {
      "text": "The rich hunters tell you how they'd like to hunt your species again."
    },
    "counter_offer_after_refusal": {
      "text": "They immediately get back to you with an offer twice as generous.",
      "choices": [
        {
          "text": "On second thought...",
          "next": [
            {
              "event": "double_payment_received"
            }
          ]
        },
        {
          "text": "Typical rich people reaction. Throwing money at the problem won’t help them here though.",
          "next": [
            {
              "event": "no_news_from_hunters"
            }
          ]
        }
      ]
    },
    "blackmail_success": {
      "text": "They're so worried about appearing manly that they accept. You get another 100 credits.",
      "effects": {
        "blackmail_payment_received": true
      }
    },
    "blackmail_failure": {
      "text": "As soon as you finish insinuating your intentions, a lawyer appears and offers you a detailed explanation of how that would be a very, very bad idea for you."
    }
  },
  "effects": {
    "base_payment_received": {
      "description": "You received a payment.",
      "type": "instant",
      "operation": "add",
      "target": "money",
      "value": 100
    },
    "double_payment_received": {
      "description": "You received a payment.",
      "type": "instant",
      "operation": "add",
      "target": "money",
      "value": 200
    },
    "blackmail_payment_received": {
      "description": "You received a payment.",
      "type": "instant",
      "operation": "add",
      "target": "money",
      "value": 100
    },
    "hunted_species": {
      "description": "Hunters have killed members of the species.",
      "type": "instant",
      "operation": "subtract",
      "target": "population",
      "value": 1
    }
  }
}

=== AcevedoR/outplant/chains/product_recall_light_sensors.json
{
  "$schema": "./schema.json",
  "title": "product recall: light sensors",
  "cooldown": 999,
  "trigger": {
    "target": "population",
    "comparator": "gte",
    "value": 3
  },
  "events": {
    "start": {
      "text": "Incoming mail:\n\nSender: support@universal-parts.univ\nSubject: IMPORTANT! PRODUCT RECALL\n\nDear customer, all products of the collection 'LIGHTSENSORS' are being recalled for false-triggering issues.\n\nPlease send them back as soon as possible, information is provided in attached document.",
      "choices": [
        {
          "text": "“Again, a spam?“ [mark as spam]",
          "next": [
            {
              "event": "minor_malfunction",
              "weight": 3
            },
            {
              "event": "major_malfunction"
            }
          ]
        },
        {
          "text": "“Do I even have any in my station?“",
          "next": [
            {
              "event": "sensors-listing-aude"
            }
          ]
        },
        {
          "text": "“I don't have time for this“ [ignore it]",
          "next": [
            {
              "event": "minor_malfunction",
              "weight": 3
            },
            {
              "event": "major_malfunction"
            }
          ]
        }
      ]
    },
    "sensors-listing-aude": {
      "text": "Aude: “There are 23 of these sensors installed in a particular hallway, they are used to turn lights on when movement is detected.“",
      "choices": [
        {
          "text": "“These lights could be turned on everyday, they would not even consume a fraction of the required resources to send this mail across the entire galaxy“ [ignore it]",
          "next": [
            {
              "event": "minor_malfunction",
              "weight": 3
            },
            {
              "event": "major_malfunction"
            }
          ]
        },
        {
          "text": "“I WILL NOT ALLOW FAULTY GEAR IN MY STATION“",
          "next": [
            {
              "event": "price-estimation"
            }
          ]
        },
        {
          "text": "“Only 23 eh? It would only take a couple of hours to dismount them“",
          "next": [
            {
              "event": "price-estimation"
            }
          ]
        }
      ]
    },
    "price-estimation": {
      "text": "You start packing up the sensors for shipping. And then think back about an add you saw recently: premium light sensors on sales from KEEPTHELIGHTSON company, it would cost you [10 €€€] shipping included.",
      "choices": [
        {
          "text": "”Why spend my hardly earned money for something that futile?” [wait for UNIVERSAL-PARTS replacement sensors]",
          "next": [
            {
              "event": "UNIVERSAL_PARTS_sensors_received"
            }
          ]
        },
        {
          "text": "”I'm not trusting UNIVERSAL-PARTS again on this, better play it safe” [order KEEPTHELIGHTSON sensors for 10 €€€]",
          "next": [
            {
              "event": "KEEPTHELIGHTSON_sensors_received"
            }
          ],
          "effects": {
            "buy_KEEPTHELIGHTSON_sensors": true
          }
        }
      ]
    },
    "KEEPTHELIGHTSON_sensors_received": {
      "text": "You received KEEPTHELIGHTSON light sensors, they work as expected, fine.",
      "choices": [
        {
          "text": "”Delightful, another source of problems out of my mind”",
          "next": [
            {
              "event": "KEEPTHELIGHTSON_end"
            }
          ]
        }
      ]
    },
    "UNIVERSAL_PARTS_sensors_received": {
      "text": "You received UNIVERSAL-PARTS light sensors, they work as expected."
    },
    "KEEPTHELIGHTSON_end": {
      "text": ""
    },
    "minor_malfunction": {
      "text": "Sometimes, some lights are already on when you go through a particular hallway, it's not a big deal."
    },
    "major_malfunction": {
      "text": "A few days after not changing your light sensors, a fire happens in that particular hallway. The area put itself in quarantine when the fire was getting to big. With no oxygen left it died rapidly.",
      "next": [
        {
          "event": "fire_reason"
        }
      ]
    },
    "fire_reason": {
      "text": "You learn by checking the logs that one light sensor suddenly did start false-triggering.. 1000 times per second! This caused the light to malfunction and ignite itself.\nThe fire damaged nearby cables inside the wall, unless you repair them, this station area is unusable.",
      "choices": [
        {
          "text": "“This station has other working areas like this, I'll be fine“ [do nothing]",
          "next": [
            {
              "event": "station_lost_one_area"
            }
          ]
        },
        {
          "text": "“All of this for some gadget light sensors!!“ [repair the wall cables for 100 €€€]",
          "next": [
            {
              "event": "wall_repaired"
            }
          ],
          "effects": {
            "repair_wall": true
          }
        }
      ]
    },
    "station_lost_one_area": {
      "text": "Your station is now missing one area"
    },
    "wall_repaired": {
      "text": "Wall is repaired, you now resort replacing the sensors",
      "next": [
        {
          "event": "price-estimation"
        }
      ]
    }
  },
  "effects": {
    "buy_KEEPTHELIGHTSON_sensors": {
      "operation": "subtract",
      "value": 10,
      "type": "instant",
      "target": "money"
    },
    "repair_wall": {
      "operation": "subtract",
      "value": 100,
      "type": "instant",
      "target": "money"
    }
  }
}

=== AcevedoR/outplant/chains/product_recall_screws.json
{
  "$schema": "./schema.json",
  "title": "product recall: screws",
  "cooldown": 999,
  "trigger": {
    "target": "population",
    "comparator": "gte",
    "value": 3
  },
  "events": {
    "start": {
      "text": "Incoming mail:\n\nSender: support@universal-parts.univ\nSubject: IMPORTANT! PRODUCT RECALL\n\nDear customer, all Type 543-B screws made 124 months ago, having a serial number between 31293920373000 and 31294072971000 are being recalled for failure issues.\n\nPlease send them back as soon as possible, more information is provided in attached document.",
      "choices": [
        {
          "text": "“Spam?“ [mark as spam]",
          "next": [
            {
              "event": "aude_estimation_major_risk",
              "in": 3
            },
            {
              "event": "failing_screw_minor",
              "weight": 10
            }
          ]
        },
        {
          "text": "“They've been working fine for now, if it's not broken, don't fix it!“ [ignore it]",
          "next": [
            {
              "event": "failing_screw_minor",
              "weight": 10
            },
            {
              "event": "aude_estimation_major_risk",
              "in": 3
            }
          ]
        },
        {
          "text": "“I better check with Aude where I used them.“",
          "next": [
            {
              "event": "aude_estimation_minor_risk"
            },
            {
              "event": "aude_estimation_major_risk"
            }
          ]
        }
      ]
    },
    "aude_estimation_minor_risk": {
      "text": "Aude: “These screws are used all around the station for storage facilities like closets, drawers, human-usable doors. It would take approximately two full days to replace them.“",
      "choices": [
        {
          "text": "“I will repair them on the spot if they break.“ [do nothing]",
          "next": [
            {
              "event": "failing_screw_minor"
            }
          ]
        }
      ]
    },
    "aude_estimation_major_risk": {
      "text": "Aude: “These screws are used in your homemade asteroids deflectors automatic turrets. It would take one day and 15 €€€ of consumable to replace them.“",
      "choices": [
        {
          "text": "”I would never let my beautiful turrets be sub-optimally assembled!” [repair them for 15 €€€]",
          "next": [
            {
              "event": "turret-repaired"
            }
          ],
          "effects": {
            "pay-turret-screws-repair": true
          }
        },
        {
          "text": "“They'll be fine.“ [do nothing]",
          "next": [
            {
              "event": "failing_screw_major",
              "in": 4
            },
            {
              "event": "nothing"
            }
          ]
        }
      ]
    },
    "turret-repaired": {
      "text": "You replaced you turrets screws, they now look brand new."
    },
    "failing_screw_minor": {
      "text": "From time to time, these Type 543-B screws, used in closets, drawers, human-usable doors, fail and you have to repair them. It's not a big deal, but it's annoying."
    },
    "failing_screw_major": {
      "text": "One day, you are woken up by a critical alarm, an asteroid did pass your station's defenses and made a hole in the hull. Emergency repairs drones were deployed and worked well.",
      "next": [
        {
          "event": "failing_screw_major_2"
        }
      ]
    },
    "failing_screw_major_2": {
      "text": "The issue was one of your homemade asteroids deflectors automatic turrets which could not rotate on the x-axis anymore because a screw broke.",
      "choices": [
        {
          "text": "“A SCREW? A DAMNED SCREW? Aude, don't tell me... is it THIS screw?“",
          "next": [
            {
              "event": "aude_answer"
            }
          ]
        }
      ]
    },
    "aude_answer": {
      "text": "Aude: “Yes, it was a Type 543-B that failed. The same type that was recalled by UNIVERSAL-PARTS some time ago, but your refused to replace them, remember?“",
      "choices": [
        {
          "text": "”You don't need to take that paternalistic tone with me. How much will it cost?”",
          "next": [
            {
              "event": "aude_price"
            }
          ]
        }
      ]
    },
    "aude_price": {
      "text": "Aude: ”Emergency one-time use drones are not cheap to operate, it will cost 200 €€€ to replenish them, and 300 €€€ to fix the hull.”",
      "choices": [
        {
          "text": "“I don't have the money right now, I will take the risk to keep things like they are.“",
          "next": [
            {
              "event": "nothing_repaired"
            }
          ]
        },
        {
          "text": "pay for repairs [500 €€€]",
          "next": [
            {
              "event": "repair-all"
            }
          ],
          "effects": {
            "pay_major": true
          }
        }
      ]
    },
    "repair-all": {
      "text": "Everything is repaired now, you changed the screws too.."
    },
    "nothing_repaired": {
      "text": "Nothing is repaired, you will have to hope no other asteroid come close any time soon."
    },
    "nothing": {
      "text": ""
    }
  },
  "effects": {
    "pay-turret-screws-repair": {
      "operation": "subtract",
      "value": 15,
      "type": "instant",
      "target": "money"
    },
    "pay_major": {
      "operation": "subtract",
      "value": 500,
      "type": "instant",
      "target": "money",
      "description": ""
    }
  }
}

=== AcevedoR/outplant/chains/rich_hunters.json
{
  "$schema": "./schema.json",
  "title": "rich hunters",
  "cooldown": 999,
  "trigger": {
    "comparator": "gt",
    "target": "population",
    "value": 8
  },
  "events": {
    "start": {
      "text": "You're contacted by some employees of very, very wealthy people. Their bosses are avid hunters and would be willing to pay loads of cash to be the first hunters of the species you're taking care of. #7kv2vq",
      "choices": [
        {
          "text": "“I guess just a fewer specimens won't hurt in the long run.” #fbxjd0",
          "effects": {
            "base_payment_received": true
          },
          "next": [
            {
              "event": "successful_hunt"
            },
            {
              "event": "unsuccessful_hunt"
            }
          ]
        },
        {
          "text": "“What? Who do they think they are? I won't let them undo all my hard work!” #nmzvao",
          "next": [
            {
              "event": "no_news_from_hunters",
              "weight": 3
            },
            {
              "event": "counter_offer_after_refusal"
            }
          ]
        }
      ]
    },
    "successful_hunt": {
      "text": "You receive the payment. A few days pass before the hunters get on the planet and successfully hunt down 10 specimens of your species. #785iko",
      "effects": {
        "hunted_species": true
      },
      "next": [
        {
          "event": "no_news_from_hunters"
        },
        {
          "event": "hunters_want_to_hunt_again"
        }
      ]
    },
    "unsuccessful_hunt": {
      "text": "You receive the payment. A few days pass before the hunters get on the planet. It turns out they aren't as good hunters as they think they are - they couldn't capture even juvenile specimens and some of them are actually wounded. #3cic55",
      "effects": {
        "base_payment_received": true
      },
      "choices": [
        {
          "text": "Pretend nothing has happened while they shamefully enter the medical bay #nthjmx",
          "next": [
            {
              "event": "no_news_from_hunters"
            }
          ]
        },
        {
          "text": "Praise them for being so skilled at “tactical retreat” #4nz2up",
          "next": [
            {
              "event": "no_news_from_hunters"
            }
          ]
        },
        {
          "text": "Try to blackmail them - either they become “generous donators” or everybody will know about just how poor hunters they are #sykd2f",
          "next": [
            {
              "event": "blackmail_success",
              "weight": 4
            },
            {
              "event": "blackmail_failure"
            }
          ]
        }
      ]
    },
    "no_news_from_hunters": {
      "text": "You never hear of the hunters again. #gbpskd"
    },
    "hunters_want_to_hunt_again": {
      "text": "The rich hunters tell you how they'd like to hunt your species again. #vifsix"
    },
    "counter_offer_after_refusal": {
      "text": "They immediately get back to you with an offer twice as generous. #7u9jw6",
      "choices": [
        {
          "text": "“On second thought...” #m8zohf",
          "effects": {
            "double_payment_received": true
          },
          "next": [
            {
              "event": "successful_hunt"
            },
            {
              "event": "unsuccessful_hunt"
            }
          ]
        },
        {
          "text": "“Typical rich people reaction. Throwing money at the problem won't help them here though.” #dmjohd",
          "next": [
            {
              "event": "no_news_from_hunters"
            }
          ]
        }
      ]
    },
    "blackmail_success": {
      "text": "They're so worried about appearing manly that they accept. You get another 100 credits. #yq9ox0",
      "effects": {
        "blackmail_payment_received": true
      }
    },
    "blackmail_failure": {
      "text": "As soon as you finish insinuating your intentions, a lawyer appears and offers you a detailed explanation of how that would be a very, very bad idea for you. #4tfjer"
    }
  },
  "effects": {
    "base_payment_received": {
      "description": "You received a payment.",
      "type": "instant",
      "operation": "add",
      "target": "money",
      "value": 100
    },
    "double_payment_received": {
      "description": "You received a payment.",
      "type": "instant",
      "operation": "add",
      "target": "money",
      "value": 200
    },
    "blackmail_payment_received": {
      "description": "You received a payment.",
      "type": "instant",
      "operation": "add",
      "target": "money",
      "value": 100
    },
    "hunted_species": {
      "description": "Hunters have killed members of the species.",
      "type": "instant",
      "operation": "subtract",
      "target": "population",
      "value": 1
    }
  }
}

=== AcevedoR/outplant/chains/starvation.json
{
  "$schema": "./schema.json",
  "title": "starvation",
  "cooldown": 10,
  "trigger": {
    "comparator": "gt",
    "target": "population",
    "value": 4
  },
  "events": {
    "start": {
      "text": "Your species is starving. #yumt26",
      "effects": {
        "reduce_growth": true
      },
      "choices": [
        {
          "text": "Do nothing. Let the strongest survive. #6f07dh",
          "next": [
            {
              "event": "choice_strongest",
              "in": 2
            }
          ]
        },
        {
          "text": "Show them how to hunt bigger prey, and so, climb the food chain. #p9n0wu",
          "next": [
            {
              "event": "choice_hunt_success",
              "in": 1
            },
            {
              "weight": 2,
              "event": "choice_hunt_failure",
              "in": 1
            }
          ]
        }
      ]
    },
    "choice_strongest": {
      "text": "You watch as your species is starving, but slowly adapting to the situation afterwards. #0sxx18",
      "next": [
        {
          "event": "choice_strongest_end"
        }
      ]
    },
    "choice_strongest_end": {
      "text": "The famine has ended as a lot of members died. #8ripkx",
      "effects": {
        "reduce_growth": false
      }
    },
    "choice_hunt_success": {
      "text": "They are better hunters now. #r3tl7p",
      "effects": {
        "better_hunting": true
      }
    },
    "choice_hunt_failure": {
      "text": "Your species is dying while trying to hunt. #k67y76",
      "effects": {
        "decrease_in_food_chain": true
      }
    }
  },
  "effects": {
    "reduce_growth": {
      "description": "You watch as your species is starving, but slowly adapting to the situation afterwards.",
      "operation": "subtract",
      "target": "population",
      "value": 1,
      "type": "permanent"
    },
    "better_hunting": {
      "description": "They are better hunters.",
      "operation": "add",
      "target": "population",
      "value": 1,
      "type": "permanent"
    },
    "decrease_in_food_chain": {
      "description": "Hunters are being hunted.",
      "operation": "subtract",
      "target": "population",
      "value": 1,
      "type": "instant"
    }
  }
}
