=== AcevedoR/outplant/event_chains/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Json schema for an event chain",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "cooldown": {
      "type": "integer",
      "minimum": 1
    },
    "trigger": {
      "type": "object",
      "properties": {
        "comparator": {
          "type": "string",
          "enum": [
            "lt",
            "lte",
            "eq",
            "gte",
            "gt"
          ]
        },
        "target": {
          "type": "string",
          "enum": [
            "population",
            "ecology",
            "money"
          ]
        },
        "value": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "required": [
        "comparator",
        "target",
        "value"
      ]
    },
    "events": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "text": {
            "type": "string"
          },
          "effects": {
            "type": "object",
            "additionalProperties": {
              "type": "boolean"
            }
          },
          "choices": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "text": {
                  "type": "string"
                },
                "next": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "event": {
                        "type": "string"
                      },
                      "in": {
                        "type": "integer",
                        "minimum": 0
                      },
                      "weight": {
                        "type": "number",
                        "exclusiveMinimum": 0
                      }
                    },
                    "required": [
                      "event"
                    ]
                  }
                }
              },
              "required": [
                "text",
                "next"
              ]
            }
          },
          "next": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "event": {
                  "type": "string"
                },
                "in": {
                  "type": "integer",
                  "minimum": 0
                },
                "weight": {
                  "type": "number",
                  "exclusiveMinimum": 0
                }
              },
              "required": [
                "event"
              ]
            }
          }
        },
        "additionalProperties": false,
        "required": [
          "text"
        ]
      },
      "required": [
        "start"
      ]
    },
    "effects": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "operation": {
            "type": "string",
            "enum": [
              "add",
              "subtract"
            ]
          },
          "target": {
            "type": "string",
            "enum": [
              "population",
              "ecology",
              "money"
            ]
          },
          "value": {
            "type": "number"
          },
          "type": {
            "type": "string",
            "enum": [
              "instant",
              "permanent"
            ]
          }
        },
        "additionalProperties": false,
        "required": [
          "operation",
          "target",
          "value",
          "type"
        ]
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "title",
    "trigger",
    "events"
  ]
}

=== AcevedoR/outplant/chains/request_additional_funding.json
{
  "$schema": "./schema.json",
  "title": "Request additional funding",
  "cooldown": 999,
  "trigger": {
    "target": "money",
    "comparator": "lte",
    "value": 10
  },
  "events": {
    "start": {
      "text": "Aude: “Wake up, the project bank account is low, you need to do something about it“",
      "choices": [
        {
          "text": "“Do you expect me to magically make money appear ?“",
          "next": [
            {
              "event": "talk-with-aude"
            }
          ]
        },
        {
          "text": "“You're right, only bad things will happen if I don't solve this.“",
          "next": [
            {
              "event": "aude-tells-you"
            }
          ]
        }
      ]
    },
    "talk-with-aude": {
      "text": "Aude: “I am designed to help you with these type of issues. Do have I to remember WHO MADE ME ?“",
      "choices": [
        {
          "text": "“I would never dare questioning your judgment.“",
          "next": [
            {
              "event": "aude-tells-you"
            }
          ]
        },
        {
          "text": "“Whatever..“",
          "next": [
            {
              "event": "aude-tells-you"
            }
          ]
        }
      ]
    },
    "aude-tells-you": {
      "text": "Aude: “You probably know what you should do, even if you're not enjoyed to. Have a bit of courage and go on with it.“",
      "choices": [
        {
          "text": "“I suppose I have no other choices..“",
          "next": [
            {
              "event": "request-funding"
            }
          ]
        }
      ]
    },
    "request-funding": {
      "text": "You spend way too much time finding out who to contact and to write the actual mail.",
      "choices": [
        {
          "text": "Ask to meet the company board to request more funding.",
          "next": [
            {
              "event": "board-meeting-accepted"
            }
          ]
        }
      ]
    },
    "board-meeting": {
      "text": "You quickly push stuff away from you webcam frame, in a vain effort to make your office look tidy.\nThe space-web meeting is about to start.\n",
      "choices": [
        {
          "text": "Connect to the meeting",
          "next": []
        }
      ]
    },
    "board-meeting-accepted": {
      "text": "You receive a (way too)fast positive response, the board has 5 minutes to spare between two meetings in.. 5 minutes.",
      "next": [
        {
          "event": "board-meeting"
        }
      ]
    }
  },
  "effects": {}
}
