=== AcevedoR/outplant/chains/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/EventChain",
  "title": "Json schema for an event chain",
  "definitions": {
    "EventChain": {
      "type": "object",
      "properties": {
        "$schema": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "cooldown": {
          "type": "integer",
          "minimum": 1
        },
        "trigger": {
          "$ref": "#/definitions/Condition"
        },
        "autoSelect": {
          "type": "boolean",
          "description": "when set to true, this chain will be selected as soon as its trigger is satisfied"
        },
        "events": {
          "type": "object",
          "additionalProperties": {
            "type": "object",
            "properties": {
              "text": {
                "type": "string"
              },
              "effects": {
                "type": "object",
                "additionalProperties": {
                  "type": "boolean"
                }
              },
              "choices": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "text": {
                      "type": "string"
                    },
                    "next": {
                      "type": "array",
                      "items": {
                        "$ref": "#/definitions/Outcome"
                      }
                    },
                    "effects": {
                      "type": "object",
                      "additionalProperties": {
                        "type": "boolean"
                      }
                    },
                    "if": {
                      "oneOf": [
                        {
                          "$ref": "#/definitions/Condition"
                        },
                        {
                          "$ref": "#/definitions/VariableCondition"
                        }
                      ]
                    }
                  },
                  "required": [
                    "text",
                    "next"
                  ],
                  "additionalProperties": false
                }
              },
              "next": {
                "type": "array",
                "items": {
                  "$ref": "#/definitions/Outcome"
                }
              }
            },
            "additionalProperties": false,
            "required": [
              "text"
            ]
          },
          "required": [
            "start"
          ]
        },
        "effects": {
          "type": "object",
          "additionalProperties": {
            "type": "object",
            "properties": {
              "description": {
                "type": "string"
              },
              "operation": {
                "type": "string",
                "enum": [
                  "add",
                  "subtract"
                ]
              },
              "target": {
                "$ref": "#/definitions/StateVariable"
              },
              "value": {
                "type": "number"
              },
              "type": {
                "type": "string",
                "enum": [
                  "instant",
                  "permanent"
                ]
              }
            },
            "additionalProperties": false,
            "required": [
              "operation",
              "target",
              "value",
              "type"
            ]
          }
        }
      },
      "additionalProperties": false,
      "required": [
        "title",
        "events"
      ]
    },
    "Outcome": {
      "type": "object",
      "properties": {
        "event": {
          "type": "string"
        },
        "in": {
          "type": "integer",
          "minimum": 0
        },
        "weight": {
          "type": "number",
          "exclusiveMinimum": 0
        },
        "effects": {
          "type": "object",
          "additionalProperties": {
            "type": "boolean"
          }
        },
        "if": {
          "oneOf": [
            {
              "$ref": "#/definitions/Condition"
            },
            {
              "$ref": "#/definitions/VariableCondition"
            }
          ]
        },
        "variables": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false,
      "required": [
        "event"
      ]
    },
    "Condition": {
      "type": "object",
      "properties": {
        "comparator": {
          "type": "string",
          "enum": [
            "lt",
            "lte",
            "eq",
            "gte",
            "gt"
          ]
        },
        "target": {
          "$ref": "#/definitions/StateVariable"
        },
        "value": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "required": [
        "comparator",
        "target",
        "value"
      ]
    },
    "VariableCondition": {
      "type": "object",
      "properties": {
        "comparator": {
          "type": "string",
          "enum": [
            "eq",
            "not"
          ]
        },
        "target": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "comparator",
        "target",
        "value"
      ]
    },
    "StateVariable": {
      "type": "string",
      "enum": [
        "population",
        "ecology",
        "money"
      ]
    }
  }
}

=== AcevedoR/outplant/test/chains/a_simple_empty_chain_with_an_hidden_choice.json
{
  "title": "a_simple_empty_chain_with_an_hidden_choice",
  "cooldown": 0,
  "autoSelect": true,
  "events": {
    "start": {
      "text": "Hello world!",
      "choices": [
        {
          "text": "an hidden choice because not enough money",
          "next": [],
          "if": {
            "comparator": "gte",
            "target": "money",
            "value": 3000000
          }
        },
        {
          "text": "a displayed choice",
          "next": []
        },
        {
          "text": "a displayed choice because enough money",
          "next": [],
          "if": {
            "comparator": "gte",
            "target": "money",
            "value": 20
          }
        }
      ]
    }
  },
  "effects": {}
}

=== AcevedoR/outplant/chains/toxic_rain.json
{
  "$schema": "./schema.json",
  "title": "toxic rain",
  "cooldown": 10,
  "events": {
    "start": {
      "text": "Your ship's sensors detect an incoming small meteorite #mm4mn8",
      "choices": [
        {
          "text": "“Probably a false positive again... Maybe one day I'll fix that damn sensor...” [ignore it] #09ef1z",
          "next": [
            {
              "event": "no_meteorite",
              "in": 2
            },
            {
              "event": "meteorite_not_dangerous",
              "in": 2
            },
            {
              "event": "toxic_meteorite",
              "in": 2,
              "weight": 2
            }
          ]
        },
        {
          "text": "“Alright, I will look at it, but only this one last time!!” #i3wplb",
          "next": [
            {
              "event": "no_meteorite"
            },
            {
              "event": "meteorite_not_dangerous_spotted"
            },
            {
              "event": "toxic_meteorite_spotted"
            }
          ]
        }
      ]
    },
    "meteorite_not_dangerous_spotted": {
      "text": "The meteorite is little and composed of rock and ice, it will disintegrate in the atmosphere, nothing to worry about. - You're not sure if the planetary collision-detection system should filter out these harmless objects. You don't remember how you configured it back in the time, and of course this is not documented. #ewdh0r",
      "next": [
        {
          "event": "meteorite_not_dangerous"
        }
      ]
    },
    "toxic_meteorite_spotted": {
      "text": "The meteorite is in reality a chemicals container ! - Some company probably rocketed it to the sky instead of paying to destroy it safely #g4ri5x",
      "choices": [
        {
          "text": "Try to guide the population to a safe area #wn0js2",
          "next": [
            {
              "event": "population_saved"
            },
            {
              "event": "population_saved_failed"
            }
          ]
        },
        {
          "text": "“They'll be fine“ [do nothing] #iu508m",
          "next": [
            {
              "event": "toxic_rain"
            }
          ]
        }
      ]
    },
    "toxic_meteorite": {
      "text": "The meteorite seems to be a toxic container, we have an issue! #hf45zz",
      "next": [
        {
          "event": "toxic_rain"
        }
      ]
    },
    "no_meteorite": {
      "text": "“No meteorite in sight eh? I'm losing my time with these sensors...“ #kec5jv"
    },
    "meteorite_not_dangerous": {
      "text": "The meteorite disintegrates while entering the atmosphere. #wy6op2"
    },
    "toxic_rain": {
      "text": "When reaching the atmosphere, the container disintegrates, causing a toxic rain. #a2sqrm",
      "effects": {
        "toxic_rain_hits_vegetation": true,
        "toxic_rain_kills_specimens": true
      }
    },
    "population_saved": {
      "text": "Your population followed your path and dodged the toxic rain #bcy1ze"
    },
    "population_saved_failed": {
      "text": "Unfortunately, your population did not follow your path to dodge the toxic rain #an4d3l",
      "effects": {
        "toxic_rain_hits_vegetation": true,
        "toxic_rain_kills_specimens": true
      }
    }
  },
  "effects": {
    "toxic_rain_hits_vegetation": {
      "description": "The toxic rain affects local vegetation",
      "operation": "subtract",
      "target": "ecology",
      "value": 1,
      "type": "permanent"
    },
    "toxic_rain_kills_specimens": {
      "description": "Some of your specimens don't survive the rain",
      "operation": "subtract",
      "target": "population",
      "value": 1,
      "type": "permanent"
    }
  }
}

=== AcevedoR/outplant/chains/science_prize.json
{
  "$schema": "./schema.json",
  "title": "science_prize",
  "cooldown": 999,
  "events": {
    "start": {
      "text": "You receive a spacemail with the following object: “Congratulations!!!! Grand science prize©®” #tdm01o",
      "choices": [
        {
          "text": "“My inbox is filled with spam like that. What did I even install a filter for?” #ztmwyt",
          "next": [
            {
              "event": "mail_deleted"
            }
          ]
        },
        {
          "text": "“Actual scientists like me don't have time to waste on frivolous things like that.” #ju866f",
          "next": [
            {
              "event": "mail_deleted"
            }
          ]
        },
        {
          "text": "“It doesn't hurt to take a look. Maybe that prize comes with some cash.” #k1xdmb",
          "next": [
            {
              "event": "open_spacemail"
            }
          ]
        },
        {
          "text": "“My work is too mediocre to deserve any prize. I won't tempt fate and get disappointed.” #k4bq3y",
          "next": [
            {
              "event": "mail_deleted"
            }
          ]
        }
      ]
    },
    "open_spacemail": {
      "text": "You read the content of the spacemail, which contains lots of blinking gifs in addition to the text: Congratulations!!!! The jury of the Grand science prize©® has selected YOU to be one of the nominees of our next edition. Everybody here will be overjoyed when you accept this fantastic opportunity to advance your career. Your contributions to important science topics have really, really impressed us. You'll find all the information about the venue attached to this spacemail. #3o71vm",
      "next": [
        {
          "event": "spacemail_asks_for_money"
        },
        {
          "event": "spacemail_read_no_money_asked"
        }
      ]
    },
    "spacemail_asks_for_money": {
      "text": "To participate, you simply have to pay very modest inscription fees (20€) to the bank account whose info you'll also find attached. #vbe09n",
      "choices": [
        {
          "text": "“Guess I got what I deserve for hoping this wouldn't be spam.” #q7nwtn",
          "next": [
            {
              "event": "mail_deleted"
            }
          ]
        },
        {
          "text": "“They can't seriously expect me to pay for a so-called “Grand science prize” I never heard about before. Scammers these days...” #jb2m95",
          "next": [
            {
              "event": "mail_deleted"
            }
          ]
        },
        {
          "text": "“I'm not a fan of how they worded their invite but you should never judge a book by its cover. I'll go!” #obido1",
          "effects": {
            "pay_for_invite": true
          },
          "next": [
            {
              "event": "invite_accepted"
            }
          ]
        },
        {
          "text": "“They seem laid back and friendly! I'll be happy to go!” #ftcajt",
          "effects": {
            "pay_for_invite": true
          },
          "next": [
            {
              "event": "invite_accepted"
            }
          ]
        },
        {
          "text": "“Who do they think they are? I'm busy doing some actual work here, no way I go to their event if they can't even pretend to have an ounce of seriousness and professional behavior in them.” #0h35li",
          "next": [
            {
              "event": "mail_deleted"
            }
          ]
        }
      ]
    },
    "spacemail_read_no_money_asked": {
      "text": "",
      "choices": [
        {
          "text": "“Guess I got what I deserve for hoping this wouldn't be spam.” #jojzr7",
          "next": [
            {
              "event": "mail_deleted"
            }
          ]
        },
        {
          "text": "“I'm not a fan of how they worded their invite but you should never judge a book by its cover. I'll go!” #ve8ys9",
          "next": [
            {
              "event": "invite_accepted"
            }
          ]
        },
        {
          "text": "“They seem laid back and friendly! I'll be happy to go!” #4s9ge5",
          "next": [
            {
              "event": "invite_accepted"
            }
          ]
        },
        {
          "text": "“Who do they think they are? I'm busy doing some actual work here, no way I go to their event if they can't even pretend to have an ounce of seriousness and professional behavior in them.” #vy17sb",
          "next": [
            {
              "event": "mail_deleted"
            }
          ]
        }
      ]
    },
    "mail_deleted": {
      "text": "You delete the spacemail. #4v7e0n"
    },
    "invite_accepted": {
      "text": "",
      "next": [
        {
          "event": "organization_mixed_up_nominees",
          "weight": 1
        },
        {
          "event": "go_to_event",
          "in": 1,
          "weight": 3
        }
      ]
    },
    "organization_mixed_up_nominees": {
      "text": "Just as you accept the invite, you get another spacemail from the Grand science prize organization. Apparently they've mixed up some names, and you're not even nominated. You can't help but feel slightly insulted that once again your work won't really be appreciated. #rx606i"
    },
    "go_to_event": {
      "text": "It's time for you to go to the Grand science prize event. Hopefully your nomination will become a win! The event conveniently takes place not so far from the planet you work on - it's on a space station only 4 systems away. #e9jzpl",
      "next": [
        {
          "event": "small_event"
        },
        {
          "event": "big_event"
        }
      ]
    },
    "small_event": {
      "text": "After some trouble finding the room for the event inside the station, you enter it only to realize there's only about half a dozen people inside, with some mismatched chairs and a meager buffet on some tables.One person from the group, wearing the most brightly colored suit you've ever seen, notices you and says: “Oh, I think everybody's here! I'm so happy everyone could make it. Let's get started!” They keep talking for over half an hour, with the most mundane and boring speech about science you've ever heard. You're about to doze off when finally the winner of the event is announced. #xvurre",
      "choices": [
        {
          "text": "Finally! #ibdyoq",
          "next": [
            {
              "event": "small_event_win"
            },
            {
              "event": "small_event_lose"
            }
          ]
        }
      ]
    },
    "small_event_win": {
      "text": "Congratulations! You can come back to your workplace with a certificate printed on flimsy paper, two encyclopedias about spacemushrooms, and a measly cashprize. At least you didn't completely waste your time like the other, less lucky nominees! #shay00",
      "effects": {
        "small_event_cashprize": true
      }
    },
    "small_event_lose": {
      "text": "You didn't win, but considering the prize turns out to consist of three coupons to buy books at a library specialized in spacemushrooms, you didn't lose that much either - if you don't think about all the time you wasted here! #dz20sv"
    },
    "big_event": {
      "text": "The event takes place in the biggest auditorium of the station - hundreds of scientists and scholars are already there. You socialize for a bit until the event properly begins. After a quick introduction speech, the results are in. #qsz897",
      "choices": [
        {
          "text": "Finally! #3zzue0",
          "next": [
            {
              "event": "big_event_win",
              "weight": 1
            },
            {
              "event": "big_event_second_place",
              "weight": 3
            },
            {
              "event": "big_event_lose",
              "weight": 6
            }
          ]
        }
      ]
    },
    "big_event_win": {
      "text": "Congratulations, you've won the grand prize! You get on stage and thank your team and the prize jury. The prize in itself is nice, but the hefty sum of money that comes with it doesn't hurt either! #e76fwg",
      "effects": {
        "big_event_cashprize": true
      }
    },
    "big_event_second_place": {
      "text": "Some other team won the grand prize, for their supposedly revolutionary research on spacemushrooms. You get an honorable mention though - and it comes with a small cash prize which is still enough to prevent you from being sad! #447qrz",
      "effects": {
        "big_event_small_cashprize": true
      }
    },
    "big_event_lose": {
      "text": "You hoped to hear your name, but you're not even part of the honorable mentions. Well, at least the food from the catering was really good, so who cares if the jury preferred a study about spacemushrooms over yours? #xkx49v"
    }
  },
  "effects": {
    "pay_for_invite": {
      "type": "instant",
      "target": "money",
      "operation": "subtract",
      "value": 20
    },
    "small_event_cashprize": {
      "type": "instant",
      "target": "money",
      "operation": "add",
      "value": 15
    },
    "big_event_cashprize": {
      "type": "instant",
      "target": "money",
      "operation": "add",
      "value": 200
    },
    "big_event_small_cashprize": {
      "type": "instant",
      "target": "money",
      "operation": "add",
      "value": 100
    }
  }
}

=== AcevedoR/outplant/event_chains/missing_form.json
{
  "$schema": "./schema.json",
  "title": "missing form",
  "cooldown": 5,
  "events": {
    "start": {
      "text": "On a unusually calm Tuesday morning, you read through your spacemails and find one from an obscure administration you've never heard about - the PETTEE (Planetoid and Exoplanet Tenaciously Tactical Executive Embassy).",
      "next": [
        {
          "event": "first_mail_content"
        }
      ]
    },
    "first_mail_content": {
      "text": "They complain about some form you were supposed to fill before being allowed to deploy a new species to the planet - one where you accept to be liable if any specimen of the species is found on another planet in the future. They're threatening you of legal repercussions if you don't pay penalties and fill the form immediately.",
      "choices": [
        {
          "text": "“That's obviously a scam!” [ignore it]",
          "next": [
            {
              "event": "no_followup_scam_suspicion",
              "in": 3,
              "weight": 1
            },
            {
              "event": "followup_scam_suspicion",
              "in": 3,
              "weight": 4
            }
          ]
        },
        {
          "text": "“I'm pretty sure they're bluffing about these penalty to scare me into paying them. I'll just fill their form.”",
          "next": [
            {
              "event": "form_filled_fine_unpaid",
              "in": 3
            },
            {
              "event": "pettee_demands_fine",
              "in": 3
            }
          ]
        },
        {
          "text": "“I can't stand losing time with any administration. I'll fill their form and pay the penalties.”",
          "next": [
            {
              "event": "pay_fine"
            }
          ]
        }
      ]
    },
    "no_followup_scam_suspicion": {
      "text": "It's been a while since you haven't had news from the PETTEE administration which was asking you to pay a fee for a missing form. Either it was an actual scam or maybe they're so disorganized they've forgotten about you."
    },
    "followup_scam_suspicion": {
      "text": "You receive another spacemail from PETTEE, that allegedly legitimate administration who wanted you to pay them and fill a form.",
      "choices": [
        {
          "text": "“These scammers don't give up easily, I'll give them that.” [keep ignoring their demands]",
          "next": [
            {
              "event": "manager_steps_in",
              "in": 3
            },
            {
              "event": "no_followup_scam_suspicion",
              "in": 3
            }
          ]
        },
        {
          "text": "“Maybe they're actually legit… I'd better do as they say.”",
          "next": [
            {
              "event": "pay_fine"
            }
          ]
        },
        {
          "text": "Pretend you've filled the form after the first warning.",
          "next": [
            {
              "event": "manager_steps_in_after_lie"
            },
            {
              "event": "cool_clerk"
            },
            {
              "event": "form_unfilled_fine_unpaid"
            }
          ]
        }
      ]
    },
    "pay_fine": {
      "text": "You pay the fine and fill the form.",
      "effects": {
        "pay_fine": true
      }
    },
    "manager_steps_in": {
      "text": "You receive a call from your manager, who sounds… angry, to say the least. “What do you mean you haven't filled the PETTEE form? Everybody knows this is like the first thing to do when introducing a new species to a planetoid or an exoplanet! Do you also need me to check if you introduced a carnivorous species to a completely vegetal world? Just pay the dang fine and send them their form or I swear to God…”",
      "next": [
        {
          "event": "pay_fine"
        }
      ]
    },
    "manager_steps_in_after_lie": {
      "text": "You soon receive a call from your manager, who sounds… angry, to say the least. “Tell me why I'm getting calls from PETTEE about you lying that you've filled a form when their records clearly show it's not the case? Even interns know filling that form is like the first thing to do when introducing a new species to a planetoid or an exoplanet! Do you also need me to check if you introduced a carnivorous species to a completely vegetal world? Just pay the dang fine and send them their form or I swear to God…”",
      "next": [
        {
          "event": "pay_fine"
        }
      ]
    },
    "cool_clerk": {
      "text": "You soon hear from an obviously very laid-back clerk from PETTEE. “Hey pal, seems like we've lost that form or whatevs, send it again plz”",
      "choices": [
        {
          "text": "[Fill the form - seems like they've forgotten the fine]",
          "next": [
            {
              "event": "form_filled_fine_unpaid",
              "in": 3
            }
          ]
        },
        {
          "text": "[Pay the fine and fill the form]",
          "next": [
            {
              "event": "pay_fine"
            }
          ]
        }
      ]
    },
    "form_filled_fine_unpaid": {
      "text": "PETTEE seems to have forgotten about you since you filled their form, even though you didn't pay their fine."
    },
    "form_unfilled_fine_unpaid": {
      "text": "PETTEE seems to have completely forgotten about you even though you neither filled their form nor payed their fine."
    },
    "pettee_demands_fine": {
      "text": "You hear back from PETTEE. They acknowledge they've received the form but are still waiting for the payment of the fine. “*Sigh* I've underestimated them…”",
      "next": [
        {
          "event": "fine_paid_after_form_filled"
        }
      ]
    },
    "fine_paid_after_form_filled": {
      "text": "You pay the fine after all.",
      "effects": {
        "pay_fine": true
      }
    }
  },
  "effects": {
    "pay_fine": {
      "type": "instant",
      "operation": "subtract",
      "target": "money",
      "value": 100
    }
  }
}

=== AcevedoR/outplant/test/chains/a_simple_chain_with_hidden_and_not_outcomes_conditioned_on_pop.json
{
  "title": "a_simple_chain_with_hidden_and_not_outcomes",
  "autoSelect": true,
  "events": {
    "start": {
      "text": "Hello world!",
      "next": [
        {
          "event": "outcome_below_3_pop",
          "if": {
            "comparator": "lt",
            "target": "population",
            "value": 3
          }
        },
        {
          "event": "outcome_above_and_eq_3_pop",
          "if": {
            "comparator": "gte",
            "target": "population",
            "value": 3
          }
        }
      ]
    },
    "outcome_below_3_pop": {
      "text": "outcome_below_3_pop",
      "effects": {}
    },
    "outcome_above_and_eq_3_pop": {
      "text": "outcome_above_and_eq_3_pop",
      "effects": {}
    }
  },
  "effects": {}
}
