=== AcevedoR/outplant/chains/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/EventChain",
  "title": "Json schema for an event chain",
  "definitions": {
    "EventChain": {
      "type": "object",
      "properties": {
        "$schema": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "cooldown": {
          "type": "integer",
          "minimum": 1
        },
        "trigger": {
          "$ref": "#/definitions/Condition"
        },
        "autoSelect": {
          "type": "boolean",
          "description": "when set to true, this chain will be selected as soon as its trigger is satisfied"
        },
        "events": {
          "type": "object",
          "additionalProperties": {
            "type": "object",
            "properties": {
              "text": {
                "type": "string"
              },
              "effects": {
                "type": "object",
                "additionalProperties": {
                  "type": "boolean"
                }
              },
              "choices": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "text": {
                      "type": "string"
                    },
                    "next": {
                      "type": "array",
                      "items": {
                        "$ref": "#/definitions/Outcome"
                      }
                    },
                    "effects": {
                      "type": "object",
                      "additionalProperties": {
                        "type": "boolean"
                      }
                    },
                    "if": {
                      "oneOf": [
                        {
                          "$ref": "#/definitions/Condition"
                        },
                        {
                          "$ref": "#/definitions/VariableCondition"
                        }
                      ]
                    }
                  },
                  "required": [
                    "text",
                    "next"
                  ],
                  "additionalProperties": false
                }
              },
              "next": {
                "type": "array",
                "items": {
                  "$ref": "#/definitions/Outcome"
                }
              }
            },
            "additionalProperties": false,
            "required": [
              "text"
            ]
          },
          "required": [
            "start"
          ]
        },
        "effects": {
          "type": "object",
          "additionalProperties": {
            "type": "object",
            "properties": {
              "description": {
                "type": "string"
              },
              "operation": {
                "type": "string",
                "enum": [
                  "add",
                  "subtract"
                ]
              },
              "target": {
                "$ref": "#/definitions/StateVariable"
              },
              "value": {
                "type": "number"
              },
              "type": {
                "type": "string",
                "enum": [
                  "instant",
                  "permanent"
                ]
              }
            },
            "additionalProperties": false,
            "required": [
              "operation",
              "target",
              "value",
              "type"
            ]
          }
        }
      },
      "additionalProperties": false,
      "required": [
        "title",
        "events"
      ]
    },
    "Outcome": {
      "type": "object",
      "properties": {
        "event": {
          "type": "string"
        },
        "in": {
          "type": "integer",
          "minimum": 0
        },
        "weight": {
          "type": "number",
          "exclusiveMinimum": 0
        },
        "effects": {
          "type": "object",
          "additionalProperties": {
            "type": "boolean"
          }
        },
        "if": {
          "oneOf": [
            {
              "$ref": "#/definitions/Condition"
            },
            {
              "$ref": "#/definitions/VariableCondition"
            }
          ]
        },
        "variables": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false,
      "required": [
        "event"
      ]
    },
    "Condition": {
      "type": "object",
      "properties": {
        "comparator": {
          "type": "string",
          "enum": [
            "lt",
            "lte",
            "eq",
            "gte",
            "gt"
          ]
        },
        "target": {
          "$ref": "#/definitions/StateVariable"
        },
        "value": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "required": [
        "comparator",
        "target",
        "value"
      ]
    },
    "VariableCondition": {
      "type": "object",
      "properties": {
        "comparator": {
          "type": "string",
          "enum": [
            "eq",
            "not"
          ]
        },
        "target": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "comparator",
        "target",
        "value"
      ]
    },
    "StateVariable": {
      "type": "string",
      "enum": [
        "population",
        "ecology",
        "money"
      ]
    }
  }
}

=== AcevedoR/outplant/chains/plans.json
{
  "$schema": "./schema.json",
  "title": "plans",
  "autoSelect": true,
  "cooldown": 5,
  "events": {
    "start": {
      "text": "It's time to define a focus for the next few months. #an4ab6",
      "effects": {
        "pop_instant_up": false,
        "pop_continuous_up": false,
        "pop_instant_down": false,
        "eco_instant_up": false,
        "eco_continuous_up": false,
        "eco_instant_down": false,
        "money_up": false,
        "money_up_a_lot": false
      },
      "choices": [
        {
          "text": "Conduct an in-depth study of the planet geography and ecosystems, then guide the species to places that will lead to maximised population growth. #tu8b6u",
          "effects": {
            "pop_instant_up": true
          },
          "next": [
            {
              "event": "end"
            }
          ]
        },
        {
          "text": "Heavily invest into cloning new specimens, to boost population growth to unprecedented levels. #gxlt5r",
          "effects": {
            "pop_continuous_up": true,
            "money_instant_down": true
          },
          "next": [
            {
              "event": "end"
            }
          ]
        },
        {
          "text": "Hunt predators of your species - its members must be protected, even if it creates ecological imbalance. #bd1341",
          "effects": {
            "eco_instant_down": true,
            "pop_continuous_up": true
          },
          "next": [
            {
              "event": "end"
            }
          ]
        },
        {
          "text": "Conduct a meta-study about the direct and indirect impacts on the biosphere the species implementation has had. #nlw9kx",
          "effects": {
            "eco_instant_up": true
          },
          "next": [
            {
              "event": "end"
            }
          ]
        },
        {
          "text": "Launch a new and ambitious plan to reinsert other species that were driven to extinction following the arrival of your species. #eeufv7",
          "effects": {
            "eco_continuous_up": true,
            "money_instant_down": true
          },
          "next": [
            {
              "event": "end"
            }
          ]
        },
        {
          "text": "Organize a large scale population control program, using hunter drones - the species has been developing far beyond a sustainable pace. #auhob7",
          "effects": {
            "pop_instant_down": true,
            "eco_continuous_up": true
          },
          "next": [
            {
              "event": "end"
            }
          ]
        },
        {
          "text": "Restrict spending to a minimum - finances aren't looking that great. #7u46tp",
          "effects": {
            "money_up": true
          },
          "next": [
            {
              "event": "end"
            }
          ]
        },
        {
          "text": "Cut down most expenses, even important ones - bankruptcy is looming. #wk98uu",
          "effects": {
            "money_up_a_lot": true,
            "eco_instant_down": true,
            "pop_instant_down": true
          },
          "next": [
            {
              "event": "end"
            }
          ]
        }
      ]
    },
    "end": {
      "text": ""
    }
  },
  "effects": {
    "pop_instant_up": {
      "type": "instant",
      "target": "population",
      "operation": "add",
      "value": 2
    },
    "pop_continuous_up": {
      "type": "permanent",
      "target": "population",
      "operation": "add",
      "value": 1
    },
    "pop_instant_down": {
      "type": "instant",
      "target": "population",
      "operation": "subtract",
      "value": 2
    },
    "eco_instant_up": {
      "type": "instant",
      "target": "ecology",
      "operation": "add",
      "value": 2
    },
    "eco_continuous_up": {
      "type": "permanent",
      "target": "ecology",
      "operation": "add",
      "value": 1
    },
    "eco_instant_down": {
      "type": "instant",
      "target": "ecology",
      "operation": "subtract",
      "value": 2
    },
    "money_instant_down": {
      "type": "instant",
      "target": "money",
      "operation": "subtract",
      "value": 400
    },
    "money_up": {
      "type": "permanent",
      "target": "money",
      "operation": "add",
      "value": 50
    },
    "money_up_a_lot": {
      "type": "permanent",
      "target": "money",
      "operation": "add",
      "value": 150
    }
  }
}

=== AcevedoR/outplant/test/chains/chain_with_variable.json
{
  "$schema": "./schema.json",
  "title": "chain_with_variable",
  "cooldown": 999,
  "autoSelect": true,
  "events": {
    "start": {
      "text": "Set a variable value",
      "next": [
        {
          "event": "second_event",
          "variables": {
            "plantType": "vegetables"
          }
        }
      ]
    },
    "second_event": {
      "text": "Second event",
      "next": [
        {
          "event": "event_vegetables",
          "if": {
            "target": "plantType",
            "comparator": "eq",
            "value": "vegetables"
          }
        },
        {
          "event": "event_not_vegetables",
          "weight": 9999999999,
          "if": {
            "target": "plantType",
            "comparator": "not",
            "value": "vegetables"
          }
        }
      ]
    },
    "event_vegetables": {
      "text": "IS OK"
    },
    "event_not_vegetables": {
      "text": "NOT OK"
    }
  },
  "effects": {}
}

=== AcevedoR/outplant/chains/high_specimens.json
{
  "$schema": "./schema.json",
  "title": "high specimens",
  "cooldown": 999,
  "events": {
    "start": {
      "text": "You get a notification from your AI assistant, AUDE. “Several drones have picked up signs of specimens behaving erratically around a specific area. Standard Protocols require you review the recorded videos.” #szmpyr",
      "choices": [
        {
          "text": "“I'll take a look!” #c2dj38",
          "next": [
            {
              "event": "review_abnormal_behavior"
            }
          ]
        }
      ]
    },
    "review_abnormal_behavior": {
      "text": "When you watch the videos, you do witness some clearly strange behaviors. Many specimens, more than usual, seems to be taking naps constantly. The ones who are awake aren't doing that much better, as they either waddle in what can't, in good faith, be called a straight line, or appear really aggressive - the number of fights is rampant. #fnb9kf",
      "choices": [
        {
          "text": "“Haha, look at that one, he tries to climb that tree but he's so clumsy he just falls everytime! I gotta share this on the SpaceInternet.” #t2pxo2",
          "next": [
            {
              "event": "video_uploaded",
              "in": 1
            }
          ]
        },
        {
          "text": "“I can't spend time on each group that displays some slightly deviant aspects here and there. AUDE, file these vids to the archives.” #5w41he",
          "next": [
            {
              "event": "specimens_die",
              "in": 2
            }
          ]
        },
        {
          "text": "“That's disturbing. We should begin to study this, and understand what's the root cause of all this.” #o94cbf",
          "next": [
            {
              "event": "study_started"
            }
          ]
        }
      ]
    },
    "video_uploaded": {
      "text": "The videos you uploaded that feature falling and sleepy specimens of your species are doing very well on the SpaceInternet, one in particular has reached meme status. You get some money from all the ad revenue. #mm1ojv",
      "next": [
        {
          "event": "specimens_die",
          "in": 2
        }
      ],
      "effects": {
        "video_uploaded": true
      }
    },
    "specimens_die": {
      "text": "A new report from AUDE indicates that most specimens from the group that displayed abnormal behaviors have died. #gj64uk",
      "effects": {
        "specimens_die": true
      }
    },
    "study_started": {
      "text": "A team is assembled and is given the task to get to the bottom of that phenomenon. #ojlmk1",
      "next": [
        {
          "event": "study_result",
          "in": 1
        }
      ]
    },
    "study_result": {
      "text": "The team you sent to study the abnormal behaviors of some group of your studies has reported its first conclusion: the change is to be blamed on spores that are released by the trees of that area. #pezzzk",
      "choices": [
        {
          "text": "“If trees are a problem, then cut the trees, and there won't be a problem anymore.” #2pu7qx",
          "next": [
            {
              "event": "trees_cut"
            }
          ]
        },
        {
          "text": "“Interesting. I'll let the exobotanists know they've got something wrong, once again.” #srx3kv",
          "next": [
            {
              "event": "specimens_die",
              "in": 1
            }
          ]
        },
        {
          "text": "“I think further study is needed. The spores cause the problem, but what causes the spores?” #f5b83d",
          "next": [
            {
              "event": "energy_drink_found",
              "in": 1
            }
          ]
        }
      ]
    },
    "trees_cut": {
      "text": "All the forests in the areas where specimens were behaving strangely are destroyed, thus removing their spores from the ecosystem. Of course, negative side effects on the environment as a whole are also to be expected. #p7btve",
      "effects": {
        "trees_cut": true
      }
    },
    "energy_drink_found": {
      "text": "While the team is picking up more samples for their tests about the strange behaviors witnessed in specimens around the area, they discover a pile of crates full of energy drinks - one of them is leaking and the drinks are spilling into an underground water lake. The ingredient list shows that it contains the same chemical component that was found in the spores causing the behavorial issues. Your team makes bet on whether the exogeologists or the exobotanists are to blame, then removes the crates. A few days later, all the specimens are behaving normally again. #7tg990"
    }
  },
  "effects": {
    "specimens_die": {
      "type": "instant",
      "target": "population",
      "operation": "subtract",
      "value": 1
    },
    "video_uploaded": {
      "type": "instant",
      "target": "money",
      "operation": "add",
      "value": 50
    },
    "trees_cut": {
      "type": "instant",
      "target": "ecology",
      "operation": "subtract",
      "value": 1
    }
  }
}

=== AcevedoR/outplant/chains/improved_drones_stealth.json
{
  "$schema": "./schema.json",
  "title": "improved drones stealth",
  "cooldown": 999,
  "events": {
    "start": {
      "text": "Your 'Ecology balance simulation' shows that the current balance in the area of your species is lower than estimated. - You think that your deployed drones are disturbing local wildlife, maybe a stealth upgrade for the drones could be a good idea. You could order it right away and hope for a fast delivery. #dcaadq",
      "choices": [
        {
          "text": "“Oh, there is a discount on the MIL-SPEC model! This module is even invisible to most sensors and emits customizable noise-canceling waves!“ [300 €€€] #y9zg0n",
          "next": [
            {
              "event": "major_drone_upgrade",
              "in": 2
            }
          ],
          "effects": {
            "major_drone_upgrade_payed": true
          }
        },
        {
          "text": "“WHAT?! All that money for a basic sound emitter and a smart holographic display, this is a scam! The cheapest one, used, on a weird discount platform, will do just fine.“ [95 €€€] #0hnn4k",
          "next": [
            {
              "event": "minor_drone_upgrade",
              "in": 4,
              "weight": 3
            },
            {
              "event": "minor_drone_upgrade_failed",
              "in": 4
            }
          ],
          "effects": {
            "minor_drone_upgrade_payed": true
          }
        },
        {
          "text": "“I'm not sure the simulation is even well calibrated, better spend money elsewhere.“ #gsfd6m",
          "next": [
            {
              "event": "no_drone_upgrade"
            }
          ]
        }
      ]
    },
    "major_drone_upgrade": {
      "text": "The drone stealth upgrade arrived, you start deploying it, and it's so satisfying to manipulate such quality product - With some tests trying different combinations, you notice that some local species you thought were fearful by nature, were actually terrified about the atrocious sound the drones were making! - The upgrade had a better positive impact on the ecology than expected! “I knew this beautiful piece of hardware would not fail me.“ #fg7i5z",
      "effects": {
        "major_ecology_impact_reduction": true
      }
    },
    "minor_drone_upgrade": {
      "text": "The drone stealth upgrade arrived, you start deploying it, right after spending hours fighting with the installation manual - The ecology is getting better, but you're not sure why. #cqh8ks",
      "effects": {
        "minor_ecology_impact_reduction": true
      }
    },
    "no_drone_upgrade": {
      "text": "You do not try to upgrade your drones. #rxkov6"
    },
    "minor_drone_upgrade_failed": {
      "text": "The drone stealth upgrade arrived, the installation manual is covered with some unknown fluids, and the module stops working after only 10 hours being deployed. “These damn space scammers!!“ #rp03hu"
    }
  },
  "effects": {
    "major_drone_upgrade_payed": {
      "type": "instant",
      "target": "money",
      "operation": "subtract",
      "value": 300
    },
    "minor_drone_upgrade_payed": {
      "type": "instant",
      "target": "money",
      "operation": "subtract",
      "value": 95
    },
    "major_ecology_impact_reduction": {
      "type": "permanent",
      "target": "ecology",
      "operation": "add",
      "value": 2
    },
    "minor_ecology_impact_reduction": {
      "type": "permanent",
      "target": "ecology",
      "operation": "add",
      "value": 1
    }
  }
}

=== AcevedoR/outplant/chains/fleeing_bees.json
{
  "$schema": "./schema.json",
  "title": "fleeing bees",
  "cooldown": 999,
  "autoSelect": true,
  "trigger": {
    "target": "population",
    "comparator": "gte",
    "value": 3
  },
  "events": {
    "start": {
      "text": "An alert is rising: the local flora is rapidly decreasing. #kv9yhr",
      "choices": [
        {
          "text": "“These plants will grow back, no need to worry” #ppdyq4",
          "next": [
            {
              "event": "issue_ignored",
              "in": 2
            }
          ]
        },
        {
          "text": "“This is strange, I should look into it” #wn7mjg",
          "next": [
            {
              "event": "investigation_finds_bees_issue"
            }
          ]
        }
      ],
      "effects": {
        "reducing_eco": true
      }
    },
    "issue_ignored": {
      "text": "The flora decrease issue is still present. #na8nzq",
      "choices": [
        {
          "text": "“I guess I'm forced to look into it...” #ho86yx",
          "next": [
            {
              "event": "investigation_finds_bees_issue"
            }
          ]
        }
      ]
    },
    "investigation_finds_bees_issue": {
      "text": "After a brief investigation, you find out the flora decrease is linked to a diminution of local bees. #jb89ax",
      "choices": [
        {
          "text": "“Bees are foundation of all biomes! Catastrophe..“ #yznv1w",
          "next": [
            {
              "event": "bees_are_decreasing"
            }
          ]
        }
      ]
    },
    "bees_are_decreasing": {
      "text": "What should you do about the diminution of bees negatively impacting the flora? #fw2cx7",
      "choices": [
        {
          "text": "Quietly send a small missile on a subset of your subjects to solve a likely overpopulation issue [100 €€€] #mjg7ys",
          "effects": {
            "missile_payed": true
          },
          "next": [
            {
              "event": "missile_sent"
            }
          ]
        },
        {
          "text": "“There must be another way. I could take some time to think about this” #ak3ukc",
          "next": [
            {
              "event": "no_bees_solution",
              "in": 2
            },
            {
              "event": "bees_solution",
              "in": 2
            }
          ]
        }
      ]
    },
    "missile_sent": {
      "text": "In the dark of the night, a divine hand takes back what is hers, leaving only destruction and crushed hopes behind her... #7l172e",
      "effects": {
        "reduced_population": true,
        "reducing_eco": false
      },
      "choices": [
        {
          "text": "“Now I am become death..“ #bxhbv8",
          "next": [
            {
              "event": "species_minor_extermination"
            }
          ]
        }
      ]
    },
    "species_minor_extermination": {
      "text": "A subset of the subjects were terminated. #tl67k9"
    },
    "no_bees_solution": {
      "text": "After intense reflexions, staring at the mirror about this flora/bees issue, no easy solution seems to appear... #bwn3lb",
      "choices": [
        {
          "text": "Do nothing and hope for the best. “Go Go bees! Hum...” #0z0z87",
          "next": [
            {
              "event": "bees_issue_still_present",
              "in": 2
            }
          ]
        },
        {
          "text": "Quietly send a small missile on a subset of your subjects to solve a likely overpopulation issue [100 €€€] #0spd2q",
          "effects": {
            "missile_payed": true
          },
          "next": [
            {
              "event": "missile_sent"
            }
          ]
        }
      ]
    },
    "bees_issue_still_present": {
      "text": "The flora/bees decrease issue is still present #hslvte",
      "next": [
        {
          "event": "bees_are_decreasing"
        }
      ]
    },
    "bees_solution": {
      "text": "Bingo! You found out your species likes to hang out near a huge plain filled with colorful flowers. - The issue is more about the flowers being crushed and eaten than overpopulation, causing bees to go elsewhere. #06yhum",
      "choices": [
        {
          "text": "“Still, just let the bees be, there were here before. May the lesson be learned” Missile the species out of the plain [100 €€€] #pe2n00",
          "effects": {
            "missile_payed": true
          },
          "next": [
            {
              "event": "missile_sent"
            }
          ]
        },
        {
          "text": "“It would take time, but I could plant more flowers with drones” #b3cfd2",
          "next": [
            {
              "event": "flower_planted",
              "in": 2
            }
          ]
        }
      ]
    },
    "flower_planted": {
      "text": "You solved the flora/bees decrease by planting more flowers to compensate your species impact. #kbdoxl",
      "effects": {
        "reducing_eco": false
      }
    }
  },
  "effects": {
    "reducing_eco": {
      "type": "permanent",
      "target": "ecology",
      "operation": "subtract",
      "value": 1
    },
    "missile_payed": {
      "type": "instant",
      "target": "money",
      "operation": "subtract",
      "value": 100
    },
    "reduced_population": {
      "type": "instant",
      "target": "population",
      "operation": "subtract",
      "value": 1
    }
  }
}
