=== AcevedoR/outplant/chains/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/EventChain",
  "title": "Json schema for an event chain",
  "definitions": {
    "EventChain": {
      "type": "object",
      "properties": {
        "$schema": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "cooldown": {
          "type": "integer",
          "minimum": 1
        },
        "trigger": {
          "$ref": "#/definitions/Condition"
        },
        "autoSelect": {
          "type": "boolean",
          "description": "when set to true, this chain will be selected as soon as its trigger is satisfied"
        },
        "events": {
          "type": "object",
          "additionalProperties": {
            "type": "object",
            "properties": {
              "text": {
                "type": "string"
              },
              "effects": {
                "type": "object",
                "additionalProperties": {
                  "type": "boolean"
                }
              },
              "choices": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "text": {
                      "type": "string"
                    },
                    "next": {
                      "type": "array",
                      "items": {
                        "$ref": "#/definitions/Outcome"
                      }
                    },
                    "effects": {
                      "type": "object",
                      "additionalProperties": {
                        "type": "boolean"
                      }
                    },
                    "if": {
                      "oneOf": [
                        {
                          "$ref": "#/definitions/Condition"
                        },
                        {
                          "$ref": "#/definitions/VariableCondition"
                        }
                      ]
                    }
                  },
                  "required": [
                    "text",
                    "next"
                  ],
                  "additionalProperties": false
                }
              },
              "next": {
                "type": "array",
                "items": {
                  "$ref": "#/definitions/Outcome"
                }
              }
            },
            "additionalProperties": false,
            "required": [
              "text"
            ]
          },
          "required": [
            "start"
          ]
        },
        "effects": {
          "type": "object",
          "additionalProperties": {
            "type": "object",
            "properties": {
              "description": {
                "type": "string"
              },
              "operation": {
                "type": "string",
                "enum": [
                  "add",
                  "subtract"
                ]
              },
              "target": {
                "$ref": "#/definitions/StateVariable"
              },
              "value": {
                "type": "number"
              },
              "type": {
                "type": "string",
                "enum": [
                  "instant",
                  "permanent"
                ]
              }
            },
            "additionalProperties": false,
            "required": [
              "operation",
              "target",
              "value",
              "type"
            ]
          }
        }
      },
      "additionalProperties": false,
      "required": [
        "title",
        "events"
      ]
    },
    "Outcome": {
      "type": "object",
      "properties": {
        "event": {
          "type": "string"
        },
        "in": {
          "type": "integer",
          "minimum": 0
        },
        "weight": {
          "type": "number",
          "exclusiveMinimum": 0
        },
        "effects": {
          "type": "object",
          "additionalProperties": {
            "type": "boolean"
          }
        },
        "if": {
          "oneOf": [
            {
              "$ref": "#/definitions/Condition"
            },
            {
              "$ref": "#/definitions/VariableCondition"
            }
          ]
        },
        "variables": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false,
      "required": [
        "event"
      ]
    },
    "Condition": {
      "type": "object",
      "properties": {
        "comparator": {
          "type": "string",
          "enum": [
            "lt",
            "lte",
            "eq",
            "gte",
            "gt"
          ]
        },
        "target": {
          "$ref": "#/definitions/StateVariable"
        },
        "value": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "required": [
        "comparator",
        "target",
        "value"
      ]
    },
    "VariableCondition": {
      "type": "object",
      "properties": {
        "comparator": {
          "type": "string",
          "enum": [
            "eq",
            "not"
          ]
        },
        "target": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "comparator",
        "target",
        "value"
      ]
    },
    "StateVariable": {
      "type": "string",
      "enum": [
        "population",
        "ecology",
        "money"
      ]
    }
  }
}

=== AcevedoR/outplant/chains/luminescent_gene.json
{
  "$schema": "../chains/schema.json",
  "title": "luminescent gene",
  "cooldown": 999,
  "events": {
    "start": {
      "text": "Temperature sensors on the planet show the climate has been unusually cold lately. Not enough to threaten the livelihood of your species though (or any of the endemic species for that matter), but the next few Winters will probably be harsher than usual on the whole ecosystem.",
      "next": [
        {
          "event": "intern_spotted_glow",
          "in": 2
        },
        {
          "event": "drone_spotted_glow",
          "in": 4
        }
      ],
      "effects": {
        "slowed_growth": true
      }
    },
    "intern_spotted_glow": {
      "text": "One of the interns in your team comes to you. They want to explain you something they saw and they're not sure whether it's normal - they seem pretty nervous. They go on to tell you how they were watching a group of specimens in playing in the snow, using a pair of advanced binoculars they took from your lab, and how they noticed the specimens emitted a light glow around them.",
      "choices": [
        {
          "text": "“That's preposterous. Next time, make sure to disable the thermic overlay of the binoculars before using them and then waste everyone's time.” The intern doesn't try to argue with you and leaves.",
          "next": [
            {
              "event": "drone_spotted_glow",
              "in": 2
            }
          ]
        },
        {
          "text": "“That's odd. Our species definitely isn't supposed to emit light. And I've never seen a specimen glow, even faintly.Thanks for bringing that up to my attention, I'll take care of it.”",
          "next": [
            {
              "event": "try_to_study_glow"
            }
          ]
        }
      ]
    },
    "drone_spotted_glow": {
      "text": "Right after the end of a particularly and needlessly long meeting with your boss, you absent-mindedly decide to take a look at the video feed from one of your surveillance drone which is currently following a group of specimens from afar.At first glance everything looks normal, but then you notice something: some sort of halo surrounds the specimens. It's like light's coming out of them, for whatever reason. You'd better find out why - you know for sure that wasn't part of your original design specs...",
      "next": [
        {
          "event": "try_to_study_glow"
        }
      ]
    },
    "try_to_study_glow": {
      "text": "“What could be the cause of this?”",
      "choices": [
        {
          "text": "Search if something has changed in the food the specimens consume",
          "next": [
            {
              "event": "try_to_study_food",
              "in": 1
            }
          ]
        },
        {
          "text": "Search in the genetic code of the species if something in their DNA is causing the glowing",
          "next": [
            {
              "event": "try_to_study_dna",
              "in": 1
            }
          ]
        },
        {
          "text": "“Now that I think of it, that looks like regular evolution to me. With colder temperatures come fewer sources of food. Creating your own light means you can search for food even in the dark, which gives a huge edge over specimens without that mutation.”",
          "next": [
            {
              "event": "laisser-faire",
              "in": 4
            }
          ]
        }
      ]
    },
    "try_to_study_food": {
      "text": "Your research to find out whether anything had changed in the food sources of your species has been frustratingly inconclusive. Nothing in your results can even begin to explain why the specimens of your species now randomly emit light.",
      "choices": [
        {
          "text": "Search in the genetic code of the species if something in their DNA is causing the glowing",
          "next": [
            {
              "event": "try_to_study_dna",
              "in": 1
            }
          ]
        },
        {
          "text": "“Now that I think of it, that looks like regular evolution to me. With colder temperatures come fewer sources of food. Creating your own light means you can search for food even in the dark, which gives a huge edge over specimens without that mutation.”",
          "next": [
            {
              "event": "laisser-faire",
              "in": 3
            }
          ]
        }
      ]
    },
    "laisser-faire": {
      "text": "The climate has finally stopped to be colder than usual. The ecosystem will probably benefit from it. Reports about glowing specimens have stopped. Maybe it wasn't that much of an advantage from an evolutionary point of view in the end.",
      "effects": {
        "slowed_growth": false
      }
    },
    "try_to_study_dna": {
      "text": "A first pass on your species's DNA doesn't give any result - there's no gene coding for a protein that would emit light. However, one scientist of your team suggests to do another, more thorough pass, and to not skip any portion of the DNA. Their intuition turns out to be fruitful: somewhere in the “filler” DNA, you find a portion coding for a luminescent protein. It's hard to tell why this section is enabled though. It's on a chromosome that's been provided by a third party private sector company, and trying to understand their obfuscated DNA is like trying to untangle a plate of spaghetti.",
      "choices": [
        {
          "text": "“Whatever. I'll find a way to fix that, there's no genome able to resist me and some CRISPR-Cas9”",
          "next": [
            {
              "event": "self_fix"
            }
          ]
        },
        {
          "text": "“No way I'm the first one who runs into that problem. I'm sure there's already a fix somewhere on the Spacenet”",
          "next": [
            {
              "event": "opensource_fix"
            }
          ]
        },
        {
          "text": "“That company is going to hear from me. We pay them a fortune and all we get is a sub-par product.”",
          "next": [
            {
              "event": "private_company_fix"
            }
          ]
        }
      ]
    },
    "self_fix": {
      "text": "You simply delete the portion of the DNA. Hopefully that won't have any side effect.",
      "next": [
        {
          "event": "fix_deployed",
          "in": 1
        }
      ]
    },
    "opensource_fix": {
      "text": "After a couple hours browsing online you finally find something useful - a blog article from a genome reseller explaining they recently received a lot of complains from their own clients, like one farmer who woke up in the middle of the night and found all of her spacecows glowing in the dark. The reseller then goes on to explain how they isolated the root cause of the issue - the culprit is the same chromosome you found the luminescent gene in. Turns out the company who created that chromosome hasn't been super thorough during their QA phase, and whenever the temperatures go below a certain threshold, the bioluminescent gene on this chromosome gets activated. The article ends with a link to download a patched version of the chromosome.",
      "choices": [
        {
          "text": "“How nice of them to share a patch! I'll use it, that will save us lots of time and money.”",
          "next": [
            {
              "event": "fix_deployed",
              "in": 1
            }
          ]
        },
        {
          "text": "“That sounds like a plausible explanation. No way I'm using a genome patch from some random blog though. I'll delete the gene myself.”",
          "next": [
            {
              "event": "self_fix"
            }
          ]
        }
      ]
    },
    "fix_deployed": {
      "text": "The new updated version of your species genome is deployed to the specimens on the planet, using drones dropping targeted enzymes. In just over a week, virtually all specimens are now treated. Some of the enzymes might have influenced other parts of the ecosystem, but you can't get high rewards without high risks, right?",
      "effects": {
        "slowed_growth": false
      }
    },
    "private_company_fix": {
      "text": "You call the company who created the faulty DNA. After waiting for almost an hour, listening to an aggravating music supposed to prevent you from growing too impatient, someone on the other end finally picks up the phone. You spend another hour trying to explain the problem, but it's pretty clear that it's an issue beyond the employee's paygrade - it takes some convincing to get them to call their supervisor. Once they come, the supervisor immediately tries to deescalate the situation. They obviously don't want the public to hear news about how they screwed up a gene - they offer to send you a patched version of the gene, accept to pay for the deployment of this version to all of your specimens using specialized drones, and even propose to give you some more money as an apology.",
      "next": [
        {
          "event": "fix_deployed",
          "in": 1
        }
      ],
      "effects": {
        "got_money_from_company": true
      }
    }
  },
  "effects": {
    "slowed_growth": {
      "type": "permanent",
      "target": "population",
      "operation": "subtract",
      "value": 1
    },
    "got_money_from_company": {
      "type": "instant",
      "target": "money",
      "operation": "add",
      "value": 500
    }
  }
}

=== AcevedoR/outplant/test/chains/ecology_permanent_drop.json
{
  "title": "starvation",
  "cooldown": 5,
  "autoSelect": true,
  "events": {
    "start": {
      "text": "permanent ecology drop",
      "effects":{
        "permanent_ecology_drop": true
      }
    }
  },
  "effects": {
    "permanent_ecology_drop": {
      "operation": "subtract",
      "value": 2,
      "type": "permanent",
      "target": "ecology"
    }
  }
}
